### ISSUE TITLE
[Feature] Jetpack lazy-load compatibility

### ISSUE THREAD

**Issue by spatsatzis** [datafeedr/ads-by-datafeedrcom#1]
Hey thanks for this plugin, I'm using it in one of my blogs. Recently I enabled Jetpack's Lazy Load feature and it works for every image except my Ads.

Obviously its normal. Lazy load filters:

`
add_filter( 'the_content', array( $this, 'add_image_placeholders' ), PHP_INT_MAX );
`
`
add_filter( 'post_thumbnail_html', array( $this, 'add_image_placeholders' ), PHP_INT_MAX );
`
`
add_filter( 'get_avatar', array( $this, 'add_image_placeholders' ), PHP_INT_MAX );
`
`
add_filter( 'widget_text', array( $this, 'add_image_placeholders' ), PHP_INT_MAX );
`
`
add_filter( 'get_image_tag', array( $this, 'add_image_placeholders' ), PHP_INT_MAX);
`

What do you think about implementing/registering a filter at your plugin (maybe at "inc/dfads.class.php" get_ads or output method) ? 

In that way I can call add_image_placeholders in my functions.php in order to leave your plugin dependent free.

Let me know what do you think about it and if you want me to develop it and create a pull request for you. :)

Thanks !

**Comment by EricBusch** [comment]
Feel free to create a PR. Thanks!

**Comment by EricBusch** [comment]
Thanks @spatsatzis! I merged your request and made a few tweaks to simplify the code as well as made a few more variables available to the filter functions. How does that work for you?

https://github.com/datafeedr/ads-by-datafeedrcom/commit/a09da6bf9a2e644576e145b598ee2bc0c0b3ddfe#diff-f4c3c258d6901819145255faa478db7f

**Comment by spatsatzis** [comment]
Great @EricBusch , I made it in 3-4 lines in order to achieve compatibility with older PHP versions. I think that passing an object property in a function like this is not supported in older versions but I'm not sure.

I like your code better, thats what I wrote in the first place but I thought about older PHP versions.

Thanks for your very fast reaction 👍

**Comment by EricBusch** [comment]
I don't think it's a problem to pass objects as parameters to functions. If it turns out to be an issue, we'll fix it.

The new code has been committed to the WordPress.org repo. 

Thanks again!
